spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://project-mysql:3306/project?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: PrimaryHikariCP
      connection-timeout: 30000

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    clean-disabled: false

  redis:
    database: 0
    host: project-redis
    port: 6379
    password: 123456
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-active: 10
        max-idle: 200
        max-wait: -1ms
